### ISSUE TITLE
wrong moves in legal_moves() could you help?

### ISSUE THREAD

**Issue by sowson** [kz04px/libchess#9]
Wrong Move: e8h8 on: 1n2k2r/2p2p1p/2b2P2/1p4B1/1P2PP2/3P3N/6B1/1N1QK2R b Kk - 0 17
![Screenshot 2022-12-24 at 13 39 46](https://user-images.githubusercontent.com/33941184/209436624-db2dcc0e-ec61-4528-a19a-098c6f6b84ae.png)

**Comment by kz04px** [comment]
I'm not too sure what's going on here. Using the above position in the `split` example shows the following output. I don't see `e8h8` in the list of moves, though I do see `e8g8` and they are both legal king side castling moves. I'll continue to look but if you have any further information it might be helpful. Please make sure you're up to date and consider running `./lichess-test` if possible, thanks.
```
./split 1 1n2k2r/2p2p1p/2b2P2/1p4B1/1P2PP2/3P3N/6B1/1N1QK2R b Kk - 0 17
-n--k--r
--p--p-p
--b--P--
-p----B-
-P--PP--
---P---N
------B-
-N-QK--R
Castling: Kk
EP: -
Turn: b

1 c6e4: 1
2 h7h6: 1
3 h7h5: 1
4 b8a6: 1
5 b8d7: 1
6 c6d5: 1
7 c6b7: 1
8 c6d7: 1
9 c6a8: 1
10 h8f8: 1
11 h8g8: 1
12 e8d7: 1
13 e8d8: 1
14 e8f8: 1
15 e8g8: 1

Time 0ms
Nodes 15
```

**Comment by sowson** [comment]
Thanks for trying to help! Do you think it is an issue? I am new to making code for chess. If you want to understand my project better, feel invited to contact https://iblog.isowa.io/contact ;-). I cannot share the details here once I use a minimal server to prototype I am trying to make with the chess backend, but I would be happy to describe what I am doing. Thanks, it is excellent code in C++!

**Comment by sowson** [comment]
Wrong Move: e8a8 on: r3kB2/7p/P5P1/2PP4/8/6PP/8/RN2KBNR b KQq - 0 25
![Screenshot 2022-12-24 at 19 22 26](https://user-images.githubusercontent.com/33941184/209447457-2d7ce073-697c-4b3c-b6ea-357a4f3586d1.png)

**Comment by sowson** [comment]
Wrong Move: e8h8 on: r1b1k2r/ppp2ppp/4p3/2b5/P2q1PP1/7P/3N4/R1BQKBNR b KQkq - 0 13
![Screenshot 2022-12-24 at 21 35 52](https://user-images.githubusercontent.com/33941184/209450417-24390178-5ae5-46c9-8548-fd337526504b.png)

**Comment by kz04px** [comment]
> I don't see `e8h8` in the list of moves, though I do see `e8g8` and they are both legal king side castling moves.

This is actually my fault. Seems like I thought my local copy of libchess was up to date, but in reality my client was just being slow to update. `e8h8` is indeed in the list of legal moves. Updated output from master with `split 1 1n2k2r/2p2p1p/2b2P2/1p4B1/1P2PP2/3P3N/6B1/1N1QK2R b Kk - 0 17` is as follows:
```
1 c6e4: 1
2 h7h6: 1
3 h7h5: 1
4 b8a6: 1
5 b8d7: 1
6 c6d5: 1
7 c6b7: 1
8 c6d7: 1
9 c6a8: 1
10 h8f8: 1
11 h8g8: 1
12 e8d7: 1
13 e8d8: 1
14 e8f8: 1
15 e8h8: 1
```

As far as I can tell, none of the moves you've shown are illegal. They're simply using the "king captures rook" notation of castling due to [chess 960](https://en.wikipedia.org/wiki/Fischer_random_chess) support. Encoding castling moves as "king to destination square" is not always sufficient for chess 960 as the following position [here](https://lichess.org/analysis/fromPosition/5k2/8/8/8/8/8/8/5K1R_w_H_-_0_1) shows. The king can either make a normal move to g1, or it can make a castling move again to g1. The move string `f1g1` would be ambiguous, where as `f1h1` can only be castling.

I suppose it's possible whatever software you're using/writing is expecting to see `e8g8` and just doesn't recognise the king capturing its rook as castling. Perhaps I'd be able to add an option for libchess to print moves in either format as desired.

**Comment by sowson** [comment]
Here is my project at https://iChess.io ;-).
![Screenshot 2022-12-25 at 02 29 17](https://user-images.githubusercontent.com/33941184/209454634-c9ef378a-0897-41ca-9300-5e0061cd9273.png)
Castling should be 1 time for the 1st time King moves 2 steps instead of the normal 1. Can you help me? Maybe as a patch because once the server gets the wrong move chess.js library on UI does not accept it, and also server may kill the process. Please do not share once I have the minimal server for the prototype. But definitely, you may play ;-). It uses AI on GPU acceleration, and it works nicely and smoothly :-).
Thank you in advance!

**Comment by sowson** [comment]
Wrong Move: e8a8 on: r3kbnr/ppp1pppp/8/2n5/1P6/N2P1P1P/P2P3P/R1BQKB1R b KQkq - 0 8
![Screenshot 2022-12-25 at 09 21 00](https://user-images.githubusercontent.com/33941184/209461425-59d2bb20-bd2c-4017-bcb3-2290b51d4cca.png)

**Comment by sowson** [comment]
Wrong Move: e1a1 on: rn2kb1r/4p3/6p1/p1q3p1/6n1/P1N2P1p/QP5P/R3K2R w KQ - 0 25
![Screenshot 2022-12-25 at 20 56 48](https://user-images.githubusercontent.com/33941184/209480532-a6a005db-969a-40b4-9c7d-8c0477cec865.png)

**Comment by sowson** [comment]
Wrong Move: e1h1 on: r2q1bnr/p1p1k1pp/2nppp2/1p6/1P6/4PNPB/P1PP1P1P/RNBQK2R w KQ b6 0 8
![Screenshot 2022-12-25 at 22 17 42](https://user-images.githubusercontent.com/33941184/209482197-086a88f6-d9d6-463f-8ab5-aa39047080af.png)

**Comment by sowson** [comment]
Those are all I found incorrect. Maybe you can tell me how to fix this issue? I was trying to understand but I am not super skilled in C++17. Thanks a lot!

**Comment by sowson** [comment]
I want to say a big thank you! I remap those for the mistaken King position in my code, and all works perfectly. Thanks for the excellent library... :D. Feel free to close this issue.

**Comment by kz04px** [comment]
> I want to say a big thank you! I remap those for the mistaken King position in my code, and all works perfectly. Thanks for the excellent library... :D. Feel free to close this issue.

I'm glad you got something to work. Sorry I didn't do this for you myself, given the time of year and some other obligations I've been quite busy recently. I hope your project goes well.
